language: cpp

compiler:
  - gcc
  - clang

env:
  - DYND_FFTW=OFF
  - DYND_FFTW=ON

before_script:
  - sudo apt-get update
  - sudo apt-get -qq install valgrind
  - if [ "$DYND_FFTW" == "ON" ]; then sudo apt-get -qq install libfftw3-dev; fi
  - mkdir build
  - cd build
  - cmake -DDYND_FFTW=${DYND_FFTW} ..

script:
  - make
  - ./tests/test_libdynd
  - valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --error-exitcode=123 ./tests/test_libdynd

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: "change"
  on_failure: "always"
