version: 2

jobs:
  "CheckFormat":
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: |
          apt-get -q update -y
          apt-get -q install -y apt-transport-https ca-certificates git gnupg software-properties-common wget
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | apt-key add -
          apt-add-repository -y 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
          apt-get -q update -y
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          apt-get -q install -y \
            clang-format-10

          update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-10 50

          scripts/check_format.sh .
  "Arch":
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run: |
          pacman -Sy
          pacman -q -S --noconfirm git
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          pacman -q -S --noconfirm \
            cmake \
            gcc \
            make
          cmake -S . -B /tmp/build
          cmake --build /tmp/build --parallel 2
          /tmp/build/tests/test_libdynd
  "Alpine":
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: |
          apk add --no-cache --no-progress git
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          apk add --no-cache --no-progress \
            cmake \
            g++ \
            gcc \
            make
          cmake -S . -B /tmp/build
          cmake --build /tmp/build --parallel 2
          /tmp/build/tests/test_libdynd
 
workflows:
  version: 2
  build:
    jobs:
      - "Alpine"
      - "Arch"
